/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.UsuarioController;
import Model.DB.UsuarioDB;
import Model.Usuario;
import Validacao.ValidacaoUsuario;
import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author joelc
 */
public class CadUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadUsuarioJ
     */
     private Connection con = null;
  
    
    public CadUsuario() {
     initComponents();
      
        DefaultTableModel modelo = (DefaultTableModel) tbUsuarios.getModel();
        tbUsuarios.setRowSorter(new TableRowSorter(modelo));
        popularTabelaUsuarios();
        txtID.setEditable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSetor = new java.awt.TextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new java.awt.TextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtRamal1 = new javax.swing.JTextPane();
        tpAdm = new javax.swing.JCheckBox();
        tpPd = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        tpTec = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        atualizarCadastro = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        txtNome = new java.awt.TextField();
        btnProcurarUsuario = new javax.swing.JButton();
        AtualizarCadastro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRamal = new java.awt.TextField();
        txtSenha = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtID = new javax.swing.JTextArea();

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Senha");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Voltar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Ramal");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tipo");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane10.setViewportView(txtRamal1);

        tpAdm.setText("Administrador");
        tpAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpAdmActionPerformed(evt);
            }
        });

        tpPd.setText("Padrão");
        tpPd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpPdActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Pesquisar");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tpTec.setText("Técnico");
        tpTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpTecActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de usuário");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Email");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Email", "Setor", "Ramal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbUsuarios);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nome");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Ex: Nome,id..");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Setor");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        atualizarCadastro.setText("Atualizar");
        atualizarCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarCadastroMouseClicked(evt);
            }
        });
        atualizarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCadastroActionPerformed(evt);
            }
        });

        btnEnviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEnviar.setText("Salvar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnProcurarUsuario.setText("Procurar");
        btnProcurarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarUsuarioActionPerformed(evt);
            }
        });

        AtualizarCadastro.setText("Alterar");
        AtualizarCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtualizarCadastroMouseClicked(evt);
            }
        });
        AtualizarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarCadastroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ID");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtID.setEditable(false);
        txtID.setColumns(20);
        txtID.setRows(1);
        txtID.setTabSize(1);
        txtID.setEnabled(false);
        jScrollPane1.setViewportView(txtID);
        txtID.getAccessibleContext().setAccessibleParent(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProcurarUsuario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tpAdm)
                                .addGap(18, 18, 18)
                                .addComponent(tpTec)
                                .addGap(18, 18, 18)
                                .addComponent(tpPd)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRamal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(jLabel1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                            .addComponent(txtSenha)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnviar)
                                .addGap(390, 390, 390)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AtualizarCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizarCadastro)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRamal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpAdm)
                    .addComponent(tpTec)
                    .addComponent(tpPd)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AtualizarCadastro)
                                .addComponent(atualizarCadastro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcurarUsuario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tpAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpAdmActionPerformed
        tpPd.setSelected(false);
        tpTec.setSelected(false);
    }//GEN-LAST:event_tpAdmActionPerformed

    private void tpPdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpPdActionPerformed
        tpAdm.setSelected(false);
        tpTec.setSelected(false);
    }//GEN-LAST:event_tpPdActionPerformed

    private void tpTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpTecActionPerformed
        tpAdm.setSelected(false);
        tpPd.setSelected(false);
    }//GEN-LAST:event_tpTecActionPerformed

    private void atualizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCadastroActionPerformed
        
        String nome = txtNome.getText();
        String setor = txtSetor.getText();
        String email = txtEmail.getText();
        int tipo = 0;
        int id = Integer.parseInt(txtID.getText());
        int ramal = Integer.parseInt(txtRamal.getText());

        String Senha = txtSenha.getText();

        if (tpAdm.isSelected()) {
            tipo = 1;

        }

        if (tpTec.isSelected()) {
            tipo = 2;
        }

        if (tpPd.isSelected()) {
            tipo = 3;
        }
        /*
        ValidacaoUsuario valida = new ValidacaoUsuario();
        
        boolean resultado;
        resultado = valida.verificaExistente(email);
        if(resultado == true){
            JOptionPane.showMessageDialog(null, "Ja existe um cadastro com o email:" +email);
        }else{

        }
        */
        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor insira o nome para cadastro !");
        } else if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor insira o email para cadastro !");
        } else if (txtSenha.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor insira uma senha para cadastro !");
        } else if (txtID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor informe o ramal  para cadastro !");
        } else if (txtSetor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor informe  o setor para cadastro !");
        } else {
            UsuarioController user = new UsuarioController();
            user.atualizarCadastro(id, nome, setor, email, ramal, Senha, tipo);
            popularTabelaUsuarios();
            JOptionPane.showMessageDialog(null, "Usuario atualizado com sucesso !");
        }
        
    }//GEN-LAST:event_atualizarCadastroActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
       
        String nome = txtNome.getText();
        String setor = txtSetor.getText();
        String email = txtEmail.getText();
        int tipo = 0;
        String ramal1 = txtRamal.getText();
        int ramal = Integer.parseInt(ramal1);

        String Senha = txtSenha.getText();
        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor insira o nome para cadastro !");
        } else if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor insira o email para cadastro !");
        } else if (txtSenha.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor insira uma senha para cadastro !");
        }  else if (txtSetor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor informe  o setor para cadastro !");
        } 

        if (tpAdm.isSelected()) {
            tipo = 1;

        }

        if (tpTec.isSelected()) {
            tipo = 2;
        }

        if (tpPd.isSelected()) {
            tipo = 3;
        }

        ValidacaoUsuario valida = new ValidacaoUsuario();
        
        boolean resultado = false;
        resultado = valida.verificaExistente(email);
        if(resultado == true){
            JOptionPane.showMessageDialog(null, "Ja existe um cadastro com o email:" +email);
        }else{

        }
        
        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor insira o nome para cadastro !");
        } else if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor insira o email para cadastro !");
        } else if (txtSenha.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor insira uma senha para cadastro !");
        }  else if (txtSetor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor informe  o setor para cadastro !");
        } else {
            UsuarioController user = new UsuarioController();
                user.cadastrarUsuario(nome, setor, email, ramal, Senha, tipo);
            popularTabelaUsuarios();
        
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnProcurarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcurarUsuarioActionPerformed

    private void atualizarCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarCadastroMouseClicked
       
       
       
    }//GEN-LAST:event_atualizarCadastroMouseClicked

    private void AtualizarCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtualizarCadastroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AtualizarCadastroMouseClicked

    private void AtualizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarCadastroActionPerformed
         int indiceLinha = tbUsuarios.getSelectedRow();
        txtID.setText(tbUsuarios.getValueAt(indiceLinha, 0).toString());
        txtNome.setText(tbUsuarios.getValueAt(indiceLinha, 1).toString());
        txtEmail.setText(tbUsuarios.getValueAt(indiceLinha, 2).toString());
        txtSetor.setText(tbUsuarios.getValueAt(indiceLinha, 3).toString());
        txtRamal.setText(tbUsuarios.getValueAt(indiceLinha, 4).toString());
        popularTabelaUsuarios();
        
    }//GEN-LAST:event_AtualizarCadastroActionPerformed

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        

       
    }//GEN-LAST:event_tbUsuariosMouseClicked
     /*
 public void preencherTabelaUsuarios(String sql){
  ArrayList dados = new ArrayList();
     String[] Colunas = new String[]{"ID", "Nome", "email", "Setor"};
     Statement stmt = null;

    
        try {
             ResultSet rs = conex.executeSql(sql);
             stmt = conex.getConnection().createStatement();
             
             rs.first();
            do{
                dados.add(new Object[]{rs.getInt("usuario_id"), rs.getString("nome"), rs.getString("email"), rs.getString("setor")});
            }while(rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar lista de usuarios");
        }
        TabelaUsuarios modelo = new TabelaUsuarios(dados, Colunas);
        tbUsuarios.setModel(modelo);
        tbUsuarios.getColumnModel().getColumn(0).setPreferredWidth(80);
        tbUsuarios.getColumnModel().getColumn(0).setResizable(false);
        tbUsuarios.getColumnModel().getColumn(1).setPreferredWidth(180);
        tbUsuarios.getColumnModel().getColumn(1).setResizable(false);
        tbUsuarios.getColumnModel().getColumn(2).setPreferredWidth(120);
        tbUsuarios.getColumnModel().getColumn(2).setResizable(false);
        tbUsuarios.getColumnModel().getColumn(3).setPreferredWidth(180);
        tbUsuarios.getColumnModel().getColumn(3).setResizable(false);
        tbUsuarios.getTableHeader().setReorderingAllowed(false);
        tbUsuarios.setAutoResizeMode(tbUsuarios.AUTO_RESIZE_OFF);
        tbUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
 }
     */
    public void popularTabelaUsuarios() {
        DefaultTableModel modelo = (DefaultTableModel) tbUsuarios.getModel();
        UsuarioController userCtrl = new UsuarioController();
        
        modelo.setNumRows(0);
        for (Usuario user : userCtrl.listarUsuarios()) {
            modelo.addRow(new Object[]{
                user.getId(),
                user.getNome(),
                user.getEmail(),
                user.getSetor(),
                user.getRamal()

            });
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarCadastro;
    private javax.swing.JButton atualizarCadastro;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnProcurarUsuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JCheckBox tpAdm;
    private javax.swing.JCheckBox tpPd;
    private javax.swing.JCheckBox tpTec;
    private java.awt.TextField txtEmail;
    private javax.swing.JTextArea txtID;
    private java.awt.TextField txtNome;
    private java.awt.TextField txtRamal;
    private javax.swing.JTextPane txtRamal1;
    private javax.swing.JPasswordField txtSenha;
    private java.awt.TextField txtSetor;
    // End of variables declaration//GEN-END:variables
}
