/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CategoriaController;
import Controller.SituacaoController;
import Model.Categoria;
import Model.Situacao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joelc
 */
public class ConfiguracoesChamado extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadCategoriaChamado
     */
    public ConfiguracoesChamado() {
        initComponents();
        popularTabelaCategoria();
        popularTabelaStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescCategoria = new javax.swing.JTextField();
        Salvar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        excluirCategoria = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        alterarStatus = new javax.swing.JButton();
        cadastrarStatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStatus = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCategoria = new javax.swing.JTable();
        alterarCategoria1 = new javax.swing.JButton();
        excluirStatus = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("                          Configurações");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 424, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cadastrar Categoria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        getContentPane().add(txtDescCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 240, 29));

        Salvar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Salvar.setText("Cadastrar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 120, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 80, 40));

        excluirCategoria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        excluirCategoria.setText("Excluir");
        excluirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(excluirCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cadastrar Status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 250, 29));

        alterarStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        alterarStatus.setText("Alterar");
        alterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarStatusActionPerformed(evt);
            }
        });
        getContentPane().add(alterarStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 120, -1));

        cadastrarStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cadastrarStatus.setText("Cadastrar");
        cadastrarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 120, -1));

        tbStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descricao"
            }
        ));
        tbStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStatusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbStatus);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 300, 120));

        tbCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descricao"
            }
        ));
        tbCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCategoriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCategoria);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 240, 120));

        alterarCategoria1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        alterarCategoria1.setText("Alterar");
        alterarCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarCategoria1ActionPerformed(evt);
            }
        });
        getContentPane().add(alterarCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 120, -1));

        excluirStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        excluirStatus.setText("Excluir");
        excluirStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirStatusActionPerformed(evt);
            }
        });
        getContentPane().add(excluirStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 90, -1));

        setSize(new java.awt.Dimension(794, 567));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        String categoria = txtDescCategoria.getText();
        boolean resultado;
        CategoriaController categoria1 = new CategoriaController();
        resultado = categoria1.inserirCategoria(categoria);
        if(resultado == true){
            JOptionPane.showMessageDialog(null, "Sucesso ao cadastrar a categoria");
            popularTabelaCategoria();
        }else{
            JOptionPane.showMessageDialog(null,"Erro ao cadastrar a categoria");
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void excluirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCategoriaActionPerformed
        int indiceLinha = tbCategoria.getSelectedRow();
        int id = (int) tbCategoria.getValueAt(indiceLinha, 0);
       
        CategoriaController cat = new CategoriaController();
        cat.deletarCategoria(id);
        popularTabelaCategoria();
    }//GEN-LAST:event_excluirCategoriaActionPerformed

    private void alterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarStatusActionPerformed
        int indiceLinha = tbStatus.getSelectedRow();
        int id = (int) tbStatus.getValueAt(indiceLinha, 0);
        if(id == 1 || id == 2){
            JOptionPane.showMessageDialog(null, "Situações: Novo e Finalizado não podem ser alteradas ou removidas");
        }else{
        String descricao = txtStatus.getText();
        SituacaoController situacao = new SituacaoController();
        situacao.atualizarSituacao(descricao, id);
        popularTabelaStatus();
        }
    }//GEN-LAST:event_alterarStatusActionPerformed

    private void cadastrarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarStatusActionPerformed
       String nome = txtStatus.getText();
       SituacaoController situ = new SituacaoController();
       boolean resultado;
       resultado = situ.criarSituacao(nome);
       if(resultado == true){
            JOptionPane.showMessageDialog(null, "Sucesso ao cadastrar o status !");
            popularTabelaStatus();
        }else{
            JOptionPane.showMessageDialog(null,"Erro ao cadastrar a categoria !");
        }
    }//GEN-LAST:event_cadastrarStatusActionPerformed

    private void tbCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCategoriaMouseClicked
        int indiceLinha = tbCategoria.getSelectedRow();
        txtDescCategoria.setText(tbCategoria.getValueAt(indiceLinha, 1).toString());
    }//GEN-LAST:event_tbCategoriaMouseClicked

    private void tbStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStatusMouseClicked
        int indiceLinha = tbStatus.getSelectedRow();
        txtStatus.setText(tbStatus.getValueAt(indiceLinha, 1).toString());
    }//GEN-LAST:event_tbStatusMouseClicked

    private void alterarCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarCategoria1ActionPerformed

    private void excluirStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirStatusActionPerformed
         int indiceLinha = tbStatus.getSelectedRow();
        int id = (int) tbStatus.getValueAt(indiceLinha, 0);
         if(id == 1 || id == 2){
            JOptionPane.showMessageDialog(null, "Situações: Novo e Finalizado não podem ser alteradas ou removidas");
        }else{
        SituacaoController situacao = new SituacaoController();
        situacao.deletarSituacao(id);
        popularTabelaStatus();
         }
    }//GEN-LAST:event_excluirStatusActionPerformed
     public void popularTabelaCategoria() {
        DefaultTableModel modelo = (DefaultTableModel) tbCategoria.getModel();
       CategoriaController categoria = new CategoriaController();
        
        modelo.setNumRows(0);
        for (Categoria cat : categoria.selecionarCategorias()) {
            modelo.addRow(new Object[]{
               cat.getId(),
               cat.getDescricao()
              

            });
           
        }
    }
     
     public void popularTabelaStatus() {
        DefaultTableModel modelo = (DefaultTableModel) tbStatus.getModel();
         SituacaoController situ = new SituacaoController();
        
        modelo.setNumRows(0);
        for (Situacao situacao : situ.selecionarSituacao()) {
            modelo.addRow(new Object[]{
               situacao.getIdSituacao(),
               situacao.getDescricao()
              

            });
          
        }
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salvar;
    private javax.swing.JButton alterarCategoria1;
    private javax.swing.JButton alterarStatus;
    private javax.swing.JButton cadastrarStatus;
    private javax.swing.JButton excluirCategoria;
    private javax.swing.JButton excluirStatus;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCategoria;
    private javax.swing.JTable tbStatus;
    private javax.swing.JTextField txtDescCategoria;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
